# Generated by Django 3.1 on 2020-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='helpContent',
            new_name='LongDescription',
        ),
        migrations.AddField(
            model_name='command',
            name='ShortDescription',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
